name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4 # clona o repositório na VM do Github Actions

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn' # usa cache automático do Yarn

      - name: Instalar dependências
        run: yarn install

      - name: Rodar Cypress
        uses: cypress-io/github-action@v5
        with:
          start: yarn start
          wait-on: 'http://localhost:3000' # ajuste para a sua porta
          wait-on-timeout: 60
        
      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
